/*
 * DotAAS Part 2 | HTTP/REST | Asset Administration Shell Repository Service Specification
 *
 * The Full Profile of the Asset Administration Shell Repository Service Specification as part of the [Specification of the Asset Administration Shell: Part 2](http://industrialdigitaltwin.org/en/content-hub).   Publisher: Industrial Digital Twin Association (IDTA) April 2023
 *
 * OpenAPI spec version: V3.0.1_SSP-001
 * Contact: info@idtwin.org
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using Newtonsoft.Json;

namespace IO.Swagger.Models
{
  
          /// <summary>
          /// Gets or Sets DataTypeIec61360
          /// </summary>
          [JsonConverter(typeof(Newtonsoft.Json.Converters.StringEnumConverter))]
          public enum DataTypeIec61360
          {
              /// <summary>
              /// Enum BLOBEnum for BLOB
              /// </summary>
              [EnumMember(Value = "BLOB")]
              BLOBEnum = 0,
              /// <summary>
              /// Enum BOOLEANEnum for BOOLEAN
              /// </summary>
              [EnumMember(Value = "BOOLEAN")]
              BOOLEANEnum = 1,
              /// <summary>
              /// Enum DATEEnum for DATE
              /// </summary>
              [EnumMember(Value = "DATE")]
              DATEEnum = 2,
              /// <summary>
              /// Enum FILEEnum for FILE
              /// </summary>
              [EnumMember(Value = "FILE")]
              FILEEnum = 3,
              /// <summary>
              /// Enum HTMLEnum for HTML
              /// </summary>
              [EnumMember(Value = "HTML")]
              HTMLEnum = 4,
              /// <summary>
              /// Enum INTEGERCOUNTEnum for INTEGER_COUNT
              /// </summary>
              [EnumMember(Value = "INTEGER_COUNT")]
              INTEGERCOUNTEnum = 5,
              /// <summary>
              /// Enum INTEGERCURRENCYEnum for INTEGER_CURRENCY
              /// </summary>
              [EnumMember(Value = "INTEGER_CURRENCY")]
              INTEGERCURRENCYEnum = 6,
              /// <summary>
              /// Enum INTEGERMEASUREEnum for INTEGER_MEASURE
              /// </summary>
              [EnumMember(Value = "INTEGER_MEASURE")]
              INTEGERMEASUREEnum = 7,
              /// <summary>
              /// Enum IRDIEnum for IRDI
              /// </summary>
              [EnumMember(Value = "IRDI")]
              IRDIEnum = 8,
              /// <summary>
              /// Enum IRIEnum for IRI
              /// </summary>
              [EnumMember(Value = "IRI")]
              IRIEnum = 9,
              /// <summary>
              /// Enum RATIONALEnum for RATIONAL
              /// </summary>
              [EnumMember(Value = "RATIONAL")]
              RATIONALEnum = 10,
              /// <summary>
              /// Enum RATIONALMEASUREEnum for RATIONAL_MEASURE
              /// </summary>
              [EnumMember(Value = "RATIONAL_MEASURE")]
              RATIONALMEASUREEnum = 11,
              /// <summary>
              /// Enum REALCOUNTEnum for REAL_COUNT
              /// </summary>
              [EnumMember(Value = "REAL_COUNT")]
              REALCOUNTEnum = 12,
              /// <summary>
              /// Enum REALCURRENCYEnum for REAL_CURRENCY
              /// </summary>
              [EnumMember(Value = "REAL_CURRENCY")]
              REALCURRENCYEnum = 13,
              /// <summary>
              /// Enum REALMEASUREEnum for REAL_MEASURE
              /// </summary>
              [EnumMember(Value = "REAL_MEASURE")]
              REALMEASUREEnum = 14,
              /// <summary>
              /// Enum STRINGEnum for STRING
              /// </summary>
              [EnumMember(Value = "STRING")]
              STRINGEnum = 15,
              /// <summary>
              /// Enum STRINGTRANSLATABLEEnum for STRING_TRANSLATABLE
              /// </summary>
              [EnumMember(Value = "STRING_TRANSLATABLE")]
              STRINGTRANSLATABLEEnum = 16,
              /// <summary>
              /// Enum TIMEEnum for TIME
              /// </summary>
              [EnumMember(Value = "TIME")]
              TIMEEnum = 17,
              /// <summary>
              /// Enum TIMESTAMPEnum for TIMESTAMP
              /// </summary>
              [EnumMember(Value = "TIMESTAMP")]
              TIMESTAMPEnum = 18          }
}
