/*
 * DotAAS Part 2 | HTTP/REST | Asset Administration Shell Repository Service Specification
 *
 * The Full Profile of the Asset Administration Shell Repository Service Specification as part of the [Specification of the Asset Administration Shell: Part 2](http://industrialdigitaltwin.org/en/content-hub).   Publisher: Industrial Digital Twin Association (IDTA) April 2023
 *
 * OpenAPI spec version: V3.0.1_SSP-001
 * Contact: info@idtwin.org
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using Newtonsoft.Json;

namespace IO.Swagger.Models
{
    /// <summary>
    /// 
    /// </summary>
    [DataContract]
    public partial class DataSpecificationIec61360 : DataSpecificationContent, IEquatable<DataSpecificationIec61360>, DataSpecificationContentChoice 
    { 
        /// <summary>
        /// Gets or Sets PreferredName
        /// </summary>
        [Required]

        [DataMember(Name="preferredName")]
        public List<LangStringPreferredNameTypeIec61360> PreferredName { get; set; }

        /// <summary>
        /// Gets or Sets ShortName
        /// </summary>

        [DataMember(Name="shortName")]
        public List<LangStringShortNameTypeIec61360> ShortName { get; set; }

        /// <summary>
        /// Gets or Sets Unit
        /// </summary>
        [RegularExpression("/^([\\t\\n\\r -퟿-�]|\\ud800[\\udc00-\\udfff]|[\\ud801-\\udbfe][\\udc00-\\udfff]|\\udbff[\\udc00-\\udfff])*$/")]
        [MinLength(1)]
        [DataMember(Name="unit")]
        public string Unit { get; set; }

        /// <summary>
        /// Gets or Sets UnitId
        /// </summary>

        [DataMember(Name="unitId")]
        public Reference UnitId { get; set; }

        /// <summary>
        /// Gets or Sets SourceOfDefinition
        /// </summary>
        [RegularExpression("/^([\\t\\n\\r -퟿-�]|\\ud800[\\udc00-\\udfff]|[\\ud801-\\udbfe][\\udc00-\\udfff]|\\udbff[\\udc00-\\udfff])*$/")]
        [MinLength(1)]
        [DataMember(Name="sourceOfDefinition")]
        public string SourceOfDefinition { get; set; }

        /// <summary>
        /// Gets or Sets Symbol
        /// </summary>
        [RegularExpression("/^([\\t\\n\\r -퟿-�]|\\ud800[\\udc00-\\udfff]|[\\ud801-\\udbfe][\\udc00-\\udfff]|\\udbff[\\udc00-\\udfff])*$/")]
        [MinLength(1)]
        [DataMember(Name="symbol")]
        public string Symbol { get; set; }

        /// <summary>
        /// Gets or Sets DataType
        /// </summary>

        [DataMember(Name="dataType")]
        public DataTypeIec61360 DataType { get; set; }

        /// <summary>
        /// Gets or Sets Definition
        /// </summary>

        [DataMember(Name="definition")]
        public List<LangStringDefinitionTypeIec61360> Definition { get; set; }

        /// <summary>
        /// Gets or Sets ValueFormat
        /// </summary>
        [RegularExpression("/^([\\t\\n\\r -퟿-�]|\\ud800[\\udc00-\\udfff]|[\\ud801-\\udbfe][\\udc00-\\udfff]|\\udbff[\\udc00-\\udfff])*$/")]
        [MinLength(1)]
        [DataMember(Name="valueFormat")]
        public string ValueFormat { get; set; }

        /// <summary>
        /// Gets or Sets ValueList
        /// </summary>

        [DataMember(Name="valueList")]
        public ValueList ValueList { get; set; }

        /// <summary>
        /// Gets or Sets Value
        /// </summary>
        [RegularExpression("/^([\\t\\n\\r -퟿-�]|\\ud800[\\udc00-\\udfff]|[\\ud801-\\udbfe][\\udc00-\\udfff]|\\udbff[\\udc00-\\udfff])*$/")]
        [StringLength(2000, MinimumLength=1)]
        [DataMember(Name="value")]
        public string Value { get; set; }

        /// <summary>
        /// Gets or Sets LevelType
        /// </summary>

        [DataMember(Name="levelType")]
        public LevelType LevelType { get; set; }

        /// <summary>
        /// Gets or Sets ModelType
        /// </summary>
        [RegularExpression("/DataSpecificationIec61360/")]
        [DataMember(Name="modelType")]
        public string ModelType { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class DataSpecificationIec61360 {\n");
            sb.Append("  PreferredName: ").Append(PreferredName).Append("\n");
            sb.Append("  ShortName: ").Append(ShortName).Append("\n");
            sb.Append("  Unit: ").Append(Unit).Append("\n");
            sb.Append("  UnitId: ").Append(UnitId).Append("\n");
            sb.Append("  SourceOfDefinition: ").Append(SourceOfDefinition).Append("\n");
            sb.Append("  Symbol: ").Append(Symbol).Append("\n");
            sb.Append("  DataType: ").Append(DataType).Append("\n");
            sb.Append("  Definition: ").Append(Definition).Append("\n");
            sb.Append("  ValueFormat: ").Append(ValueFormat).Append("\n");
            sb.Append("  ValueList: ").Append(ValueList).Append("\n");
            sb.Append("  Value: ").Append(Value).Append("\n");
            sb.Append("  LevelType: ").Append(LevelType).Append("\n");
            sb.Append("  ModelType: ").Append(ModelType).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public  new string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="obj">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object obj)
        {
            if (ReferenceEquals(null, obj)) return false;
            if (ReferenceEquals(this, obj)) return true;
            return obj.GetType() == GetType() && Equals((DataSpecificationIec61360)obj);
        }

        /// <summary>
        /// Returns true if DataSpecificationIec61360 instances are equal
        /// </summary>
        /// <param name="other">Instance of DataSpecificationIec61360 to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(DataSpecificationIec61360 other)
        {
            if (ReferenceEquals(null, other)) return false;
            if (ReferenceEquals(this, other)) return true;

            return 
                (
                    PreferredName == other.PreferredName ||
                    PreferredName != null &&
                    PreferredName.SequenceEqual(other.PreferredName)
                ) && 
                (
                    ShortName == other.ShortName ||
                    ShortName != null &&
                    ShortName.SequenceEqual(other.ShortName)
                ) && 
                (
                    Unit == other.Unit ||
                    Unit != null &&
                    Unit.Equals(other.Unit)
                ) && 
                (
                    UnitId == other.UnitId ||
                    UnitId != null &&
                    UnitId.Equals(other.UnitId)
                ) && 
                (
                    SourceOfDefinition == other.SourceOfDefinition ||
                    SourceOfDefinition != null &&
                    SourceOfDefinition.Equals(other.SourceOfDefinition)
                ) && 
                (
                    Symbol == other.Symbol ||
                    Symbol != null &&
                    Symbol.Equals(other.Symbol)
                ) && 
                (
                    DataType == other.DataType ||
                    DataType != null &&
                    DataType.Equals(other.DataType)
                ) && 
                (
                    Definition == other.Definition ||
                    Definition != null &&
                    Definition.SequenceEqual(other.Definition)
                ) && 
                (
                    ValueFormat == other.ValueFormat ||
                    ValueFormat != null &&
                    ValueFormat.Equals(other.ValueFormat)
                ) && 
                (
                    ValueList == other.ValueList ||
                    ValueList != null &&
                    ValueList.Equals(other.ValueList)
                ) && 
                (
                    Value == other.Value ||
                    Value != null &&
                    Value.Equals(other.Value)
                ) && 
                (
                    LevelType == other.LevelType ||
                    LevelType != null &&
                    LevelType.Equals(other.LevelType)
                ) && 
                (
                    ModelType == other.ModelType ||
                    ModelType != null &&
                    ModelType.Equals(other.ModelType)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                var hashCode = 41;
                // Suitable nullity checks etc, of course :)
                    if (PreferredName != null)
                    hashCode = hashCode * 59 + PreferredName.GetHashCode();
                    if (ShortName != null)
                    hashCode = hashCode * 59 + ShortName.GetHashCode();
                    if (Unit != null)
                    hashCode = hashCode * 59 + Unit.GetHashCode();
                    if (UnitId != null)
                    hashCode = hashCode * 59 + UnitId.GetHashCode();
                    if (SourceOfDefinition != null)
                    hashCode = hashCode * 59 + SourceOfDefinition.GetHashCode();
                    if (Symbol != null)
                    hashCode = hashCode * 59 + Symbol.GetHashCode();
                    if (DataType != null)
                    hashCode = hashCode * 59 + DataType.GetHashCode();
                    if (Definition != null)
                    hashCode = hashCode * 59 + Definition.GetHashCode();
                    if (ValueFormat != null)
                    hashCode = hashCode * 59 + ValueFormat.GetHashCode();
                    if (ValueList != null)
                    hashCode = hashCode * 59 + ValueList.GetHashCode();
                    if (Value != null)
                    hashCode = hashCode * 59 + Value.GetHashCode();
                    if (LevelType != null)
                    hashCode = hashCode * 59 + LevelType.GetHashCode();
                    if (ModelType != null)
                    hashCode = hashCode * 59 + ModelType.GetHashCode();
                return hashCode;
            }
        }

        #region Operators
        #pragma warning disable 1591

        public static bool operator ==(DataSpecificationIec61360 left, DataSpecificationIec61360 right)
        {
            return Equals(left, right);
        }

        public static bool operator !=(DataSpecificationIec61360 left, DataSpecificationIec61360 right)
        {
            return !Equals(left, right);
        }

        #pragma warning restore 1591
        #endregion Operators
    }
}
